version: '3'
networks:
  backend:
    driver: bridge
services:
  postgres:
    image: postgres:12
    container_name: postgres-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - backend
  app:
    build: .
    container_name: users-api
    ports:
      - 8080:8080
    environment:
      - DATABASE_NAME=users
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=admin
    depends_on:
      - postgres
    networks:
      - backend